apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
        what: demo        
    spec:
      containers:
      - name: producer
        image: ghcr.io/modulus/ampq-demo-producer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SERVER
            value: "amqp://someone:nothing@quotes-rabbitmq-headless:5672"
          - name: RUST_LOG
            value: INFO
          - name: RUST_BACKTRACE
            value: full
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
        what: demo              
    spec:
      containers:
      - name: consumer
        image: ghcr.io/modulus/ampq-demo-consumer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SERVER
            value: "amqp://someone:nothing@quotes-rabbitmq-headless:5672"
          - name: RUST_LOG
            value: INFO
          - name: RUST_BACKTRACE
            value: full            