name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build producer
      run: cargo build --bin producer --verbose
    - name: Build consumer
      run: cargo build --bin consumer --verbose
    - name: Run tests
      run: cargo test --verbose
  package:
    needs: build 
    runs-on: ubuntu-latest    
    strategy:
      max-parallel: 2    
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build producer
        run: docker build -t ghcr.io/modulus/ampq-demo-producer:latest -f Dockerfile.producer .
      - name: Docker push
        run: docker push ghcr.io/modulus/ampq-demo-producer:latest
      - name: Docker build consumer
        run: docker build -t ghcr.io/modulus/ampq-demo-consumer:latest -f Dockerfile.consumer .
      - name: Push consumer container
        run: docker push ghcr.io/modulus/ampq-demo-consumer:latest 